name: test

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: latest

            - name: Install shards
              run: shards install

            - name: Run format check
              run: crystal tool format --check

            - name: Run Ameba
              run: ameba
